linters:
  DuplicateProperty:
    enabled: false

  ElsePlacement:
    enabled: false

  SpaceAroundOperator:
    enabled: false

  SpaceBetweenParens:
    enabled: false

  VendorPrefix:
    enabled: false